version: "3.7"

services: 

  influxdb:
    build: influxdb
    container_name: influxdb
    image: influxdb-rpi
    env_file:
      - config.env
    ports:
      - "8086:8086" # This is the HTTP port
    volumes:
      - ../influxdb_data:/var/lib/influxdb
    networks:
      - influxdb

  telegraf:
    image: alexswilliams/arm32v6-telegraf:1.13.1
    container_name: telegraf
    networks:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

#   chronograf:
#     image: chronograf:1.8
#     container_name: chronograf
#     ports:
#       - "8888:8888"
#     networks:
#       - influxdb

#   grafana:
#     image: grafana/grafana:6.7.1
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     networks:
#       - influxdb
#     # volumes:
#       # - ~/projects/docker/grafana/data:/var/lib/grafana

networks:
  # Make a network connecting all containers seamlessly
  influxdb:
